workflows:
  ios-cordova-build:
    name: Build iOS Cordova

    environment:
      node: 12.13.0
      xcode: 15.0
      vars:
        CORDOVA_IOS_VERSION: "6.2.0"

    scripts:
      - name: Instalar Cordova e dependências
        script: |
          npm install -g npm@6.12.0
          npm install -g cordova@11.1.0
          npm install

      - name: Preparar plataforma iOS
        script: |
          cordova platform remove ios || true
          cordova platform add ios@${CORDOVA_IOS_VERSION}

      - name: Construir IPA
        script: |
          cordova build ios --release --device

    artifacts:
      - platforms/ios/build/device/*.ipa
