workflows:
  ios-cordova-signed:
    name: Build iOS Cordova (Signed IPA)

    environment:
      node: 14.20.0
      xcode: 16.1
      vars:
        CORDOVA_IOS_VERSION: "6.2.0"

    scripts:
      - name: Instalar Cordova e dependências
        script: |
          npm install -g npm@6.14.17
          npm install -g cordova@11.1.0
          npm install

      - name: Remover plataforma Android
        script: |
          cordova platform remove android || true

      - name: Preparar plataforma iOS
        script: |
          cordova platform remove ios || true
          cordova platform add ios@${CORDOVA_IOS_VERSION}

      - name: Permitir execução do script de correção
        script: |
          chmod +x fix_signing.sh

      - name: Limpar assinaturas manuais e forçar Automatic Signing
        script: |
          ./fix_signing.sh

      - name: Build iOS com assinatura automática
        script: |
          cordova build ios --release --device --buildConfig=build.json -- --allowProvisioningUpdates

    artifacts:
      - platforms/ios/build/device/*.ipa
      - platforms/ios/build/**/*.xcarchive
