workflows:
  ios_testflight:
    name: "iOS Release – TestFlight (Ionic + Cordova)"
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      node: latest
      npm: default
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "br.acol.com.saudi.acompanhamento.medico"
    scripts:
      - name: Install global CLIs
        script: |
          npm install -g @ionic/cli cordova

      - name: Install project dependencies
        script: |
          npm ci

      - name: Ionic build (web assets)
        script: |
          ionic build --prod

      - name: Add iOS platform (Cordova)
        script: |
          cordova platform remove ios || true
          cordova platform add ios

      - name: Prepare Cordova iOS project
        script: |
          ionic cordova prepare ios

      - name: Build Xcode archive
        script: |
          cd platforms/ios
          xcodebuild \
            -workspace $(ls *.xcworkspace) \
            -scheme $(ls | grep .xcodeproj | sed 's/.xcodeproj//') \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
